/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as appNoteRouteImport } from './routes/(app)/note'

const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appNoteRoute = appNoteRouteImport.update({
  id: '/(app)/note',
  path: '/note',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/note': typeof appNoteRoute
  '/login': typeof authLoginRoute
}
export interface FileRoutesByTo {
  '/note': typeof appNoteRoute
  '/login': typeof authLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)/note': typeof appNoteRoute
  '/(auth)/login': typeof authLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/note' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/note' | '/login'
  id: '__root__' | '/(app)/note' | '/(auth)/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appNoteRoute: typeof appNoteRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/note': {
      id: '/(app)/note'
      path: '/note'
      fullPath: '/note'
      preLoaderRoute: typeof appNoteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  appNoteRoute: appNoteRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
